[comics]
#to include a list of comics, paste a list of rss links:
#rss_links = [
		#"https://example1/rss.xml",
		#"https://example2/rss.xml",
	#]
rss_links = []

#for each recipe you want to use, create a table entry. The must be a recipe created by calibre with exactly the same name. Optionnaly, you can add a user and password if the recipe requires credentials
[[recipes]]
name = your_recipe_name

[[recipees]]
name = another_recipe_name
user = your_username
password = your_password

[webdav]
#create a webdav shared folder and paste the link here
link = "https://example.com/abc"
