[comics]
#to include a list of comics, paste a list of rss links:
#rss_links = [
		#"https://example1/rss.xml",
		#"https://example2/rss.xml",
	#]
rss_links = []

[credentials]
#for each recipe you want to use, create a section. The must be a recipe created by calibre with exactly the same name. Optionnaly, you can add a user and password if the recipe requires credentials
	#[recipe_name1]
	#user = "user1"
	#password = "password1"

	#[recipe_name2]

[webdav]
#create a webdav shared folder and paste the link here
link = "https://example.com/abc"
